# fly.toml app configuration file generated for to-dos-pwa-react on 2024-01-26T10:34:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "to-dos-pwa-react"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
